<div class="alert alert-block alert-danger">  
<h2><center><strong>Importing Python Libraries 📕 📗 📘 📙</strong></center></h2>
        
</div>

In [1]:
import re
import requests
import pandas as pd
import numpy as np
import os
import glob
from prettytable import PrettyTable
from bs4 import BeautifulSoup
pd.options.display.max_columns = None
from numpy import loadtxt
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis  import LinearDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings("ignore")

<div class="alert alert-block alert-info">  
<h2><center><strong>Web Scraping & Analysis of English Premier League (EPL)📁 📂</strong></center></h2>
        
</div>

In [2]:
#scraping the base url form the website www.football-data.co.uk
url="https://www.football-data.co.uk/englandm.php"

# Make a GET request to fetch the raw HTML content
html_content = requests.get(url).text

# Parse the html content
soup = BeautifulSoup(html_content, "lxml")

#print(soup.prettify()) # print the parsed data of html

Creating a list of all the csv files scraped from the website. This code will scrape any new season data that is uploaded on the website.

In [3]:
data = []

''' removing unwanted season as the dataset attribute format does not match the format of the newer data
unwanted = ['Season 1993/1994','Season 1994/1995','Season 1995/1996','Season 1996/1997','Season 1997/1998',
'Season 1998/1999','Season 1999/2000','Season 2000/2001','Season 2001/2002'] '''

for link in soup.find_all('a', href=True, text=re.compile('Premier League')):
    data.append("https://www.football-data.co.uk/"+link.get("href"))

data = data[1:20]
print(data)

len(data)

['https://www.football-data.co.uk/mmz4281/2021/E0.csv', 'https://www.football-data.co.uk/mmz4281/1920/E0.csv', 'https://www.football-data.co.uk/mmz4281/1819/E0.csv', 'https://www.football-data.co.uk/mmz4281/1718/E0.csv', 'https://www.football-data.co.uk/mmz4281/1617/E0.csv', 'https://www.football-data.co.uk/mmz4281/1516/E0.csv', 'https://www.football-data.co.uk/mmz4281/1415/E0.csv', 'https://www.football-data.co.uk/mmz4281/1314/E0.csv', 'https://www.football-data.co.uk/mmz4281/1213/E0.csv', 'https://www.football-data.co.uk/mmz4281/1112/E0.csv', 'https://www.football-data.co.uk/mmz4281/1011/E0.csv', 'https://www.football-data.co.uk/mmz4281/0910/E0.csv', 'https://www.football-data.co.uk/mmz4281/0809/E0.csv', 'https://www.football-data.co.uk/mmz4281/0708/E0.csv', 'https://www.football-data.co.uk/mmz4281/0607/E0.csv', 'https://www.football-data.co.uk/mmz4281/0506/E0.csv', 'https://www.football-data.co.uk/mmz4281/0405/E0.csv', 'https://www.football-data.co.uk/mmz4281/0304/E0.csv', 'https://

19

Reading all the csv files and appending it to a single dataset. The code piece df{i} will dynamically take in any season data which is scraped from the website.

In [4]:
frames = []

for i in range(len(data)):
    globals()[f"df{i}"] = pd.read_csv(data[i], encoding="latin-1", on_bad_lines='skip')
    df_object = globals()[f"df{i}"]
    frames.append(df_object)

In [5]:
df = pd.DataFrame()
for d in frames:
    df =  df.append(d, ignore_index=True)

<div class="alert alert-block alert-danger">  
<h2><center><strong>Exploratory data analysis 🔎 📊</strong></center></h2>
        
</div>

#### Five top records of data

In [6]:
df.head()

Div        Date   Time        HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  12/09/2020  12:30          Fulham      Arsenal   0.0   3.0   A   0.0   
1  E0  12/09/2020  15:00  Crystal Palace  Southampton   1.0   0.0   H   1.0   
2  E0  12/09/2020  17:30       Liverpool        Leeds   4.0   3.0   H   3.0   
3  E0  12/09/2020  20:00        West Ham    Newcastle   0.0   2.0   A   0.0   
4  E0  13/09/2020  14:00       West Brom    Leicester   0.0   3.0   A   0.0   

   HTAG HTR     Referee    HS    AS  HST  AST    HF    AF   HC   AC   HY   AY  \
0   1.0   A  C Kavanagh   5.0  13.0  2.0  6.0  12.0  12.0  2.0  3.0  2.0  2.0   
1   0.0   H      J Moss   5.0   9.0  3.0  5.0  14.0  11.0  7.0  3.0  2.0  1.0   
2   2.0   H    M Oliver  22.0   6.0  6.0  3.0   9.0   6.0  9.0  0.0  1.0  0.0   
3   0.0   D   S Attwell  15.0  15.0  3.0  2.0  13.0   7.0  8.0  7.0  2.0  2.0   
4   0.0   D    A Taylor   7.0  13.0  1.0  7.0  12.0   9.0  2.0  5.0  1.0  1.0   

    HR   AR  B365H  B365D  B365A   BWH   BWD    BWA   IWH   IWD   IWA   PSH  \
0  0.0  0.0   6.00   4.33   1.53  5.50  4.25   1.57  6.00  3.90  1.57  6.16   
1  0.0  0.0   3.10   3.25   2.37  3.00  3.20   2.45  3.15  2.95  2.40  3.32   
2  0.0  0.0   1.28   6.00   9.50  1.26  6.25  10.50  1.35  5.00  8.50  1.31   
3  0.0  0.0   2.15   3.40   3.40  2.15  3.40   3.40  2.15  3.15  3.40  2.18   
4  0.0  0.0   3.80   3.60   1.95  3.70  3.60   2.00  3.85  3.20  2.00  4.00   

    PSD   PSA   WHH  WHD    WHA   VCH   VCD    VCA  MaxH  MaxD   MaxA  AvgH  \
0  4.51  1.56  6.50  4.2   1.53  6.50  4.20   1.55  6.55  4.55   1.60  5.94   
1  3.29  2.40  3.20  3.2   2.35  3.20  3.20   2.40  3.36  3.36   2.50  3.18   
2  6.25  9.92  1.27  6.0  10.00  1.30  5.75  10.50  1.35  6.50  10.75  1.30   
3  3.61  3.50  2.15  3.5   3.40  2.15  3.40   3.60  2.24  3.70   3.60  2.15   
4  3.59  2.00  3.80  3.6   1.95  4.00  3.50   1.95  4.00  3.82   2.04  3.87   

   AvgD  AvgA  B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  \
0  4.34  1.55      1.72      2.10   1.80   2.13     1.84     2.18     1.76   
1  3.22  2.39      2.20      1.66   2.34   1.68     2.36     1.73     2.24   
2  5.96  9.68      1.53      2.50   1.56   2.60     1.56     2.68     1.52   
3  3.48  3.42      1.90      1.90   2.00   1.91     2.05     1.95     1.97   
4  3.57  1.97      1.90      1.90   2.00   1.91     2.02     2.03     1.92   

   Avg<2.5   AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  \
0     2.10  1.00     1.93     1.97  1.96  1.96    2.00    1.99    1.93   
1     1.67  0.25     1.85     2.05  1.88  2.05    1.88    2.07    1.84   
2     2.53 -1.50     1.95     1.95  1.97  1.95    2.00    2.08    1.90   
3     1.86 -0.50     2.07     1.72  2.17  1.78    2.17    1.81    2.12   
4     1.90  0.50     1.91     1.99  1.92  2.00    1.93    2.02    1.88   

   AvgAHA  B365CH  B365CD  B365CA  BWCH  BWCD   BWCA  IWCH  IWCD  IWCA  PSCH  \
0    1.95    5.00    4.00    1.66  5.50  4.00   1.62  5.25  3.90  1.67  5.48   
1    2.03    3.00    3.25    2.40  3.00  3.30   2.40  3.05  2.90  2.45  3.09   
2    1.97    1.25    6.00   11.00  1.25  6.25  11.00  1.30  6.00  9.00  1.28   
3    1.75    1.95    3.60    3.75  1.95  3.70   3.75  2.05  3.25  3.75  2.04   
4    1.97    3.25    3.40    2.20  3.30  3.40   2.20  3.35  3.00  2.30  3.38   

   PSCD   PSCA  WHCH  WHCD   WHCA  VCCH  VCCD   VCCA  MaxCH  MaxCD  MaxCA  \
0  3.98   1.69  5.50   3.8   1.65  5.50  3.90   1.67   5.75   4.20   1.71   
1  3.27   2.54  3.10   3.1   2.45  3.10  3.25   2.45   3.25   3.33   2.55   
2  6.34  11.38  1.25   6.0  12.00  1.29  6.00  11.50   1.30   6.75  12.27   
3  3.59   3.92  2.00   3.5   3.80  2.00  3.50   3.90   2.07   3.78   3.99   
4  3.38   2.32  3.30   3.3   2.25  3.30  3.30   2.30   3.55   3.50   2.38   

   AvgCH  AvgCD  AvgCA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  \
0   5.36   3.93   1.67        2.0       1.80    2.06    1.86      2.10   
1   3.08   3.22   2.47        2.2       1.66    2.26    1.72      2.27   
2   1.28  

#### Five last records of data

In [7]:
df.tail()

Div        Date Time    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
7126  E0  11/05/2003  NaN       Leeds  Aston Villa   3.0   1.0   H   1.0   
7127  E0  11/05/2003  NaN    Man City  Southampton   0.0   1.0   A   0.0   
7128  E0  11/05/2003  NaN  Sunderland      Arsenal   0.0   4.0   A   0.0   
7129  E0  11/05/2003  NaN   Tottenham    Blackburn   0.0   4.0   A   0.0   
7130  E0  11/05/2003  NaN   West Brom    Newcastle   2.0   2.0   D   0.0   

      HTAG HTR   Referee    HS    AS  HST   AST    HF    AF    HC    AC   HY  \
7126   1.0   D  M Halsey  11.0  18.0  5.0   6.0  18.0  14.0   1.0   8.0  0.0   
7127   1.0   A    M Dean  17.0   6.0  7.0   3.0  14.0  14.0  10.0   4.0  3.0   
7128   2.0   A  P Durkin   7.0  20.0  3.0  13.0  16.0  12.0   6.0  10.0  1.0   
7129   2.0   A  A D'Urso  11.0  13.0  7.0   9.0   9.0  12.0   6.0   3.0  1.0   
7130   1.0   A  G Barber   8.0  14.0  3.0   9.0   9.0   8.0   2.0   8.0  0.0   

       AY   HR   AR  B365H  B365D  B365A  BWH  BWD  BWA  IWH  IWD  IWA  PSH  \
7126  1.0  0.0  0.0  1.833   3.25  3.750  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
7127  4.0  0.0  0.0  1.615   3.40  5.000  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
7128  0.0  0.0  0.0  5.000   3.40  1.615  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
7129  1.0  1.0  0.0  2.500   3.50  2.300  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
7130  0.0  0.0  0.0  4.000   3.50  1.727  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

      PSD  PSA   WHH  WHD   WHA  VCH  VCD  VCA  MaxH  MaxD  MaxA  AvgH  AvgD  \
7126  NaN  NaN  1.80  3.3  3.75  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN   
7127  NaN  NaN  1.61  3.5  4.50  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN   
7128  NaN  NaN  4.20  3.5  1.66  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN   
7129  NaN  NaN  2.62  3.5  2.20  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN   
7130  NaN  NaN  3.75  3.3  1.80  NaN  NaN  NaN   NaN   NaN   NaN   NaN   NaN   

      AvgA  B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  \
7126   NaN      1.80      2.00    NaN    NaN      NaN      NaN      NaN   
7127   NaN      1.75      2.05    NaN    NaN      NaN      NaN      NaN   
7128   NaN      1.75      2.05    NaN    NaN      NaN      NaN      NaN   
7129   NaN      1.85      1.95    NaN    NaN      NaN      NaN      NaN   
7130   NaN      1.80      2.00    NaN    NaN      NaN      NaN      NaN   

      Avg<2.5  AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  \
7126      NaN  NaN      NaN      NaN   NaN   NaN     NaN     NaN     NaN   
7127      NaN  NaN      NaN      NaN   NaN   NaN     NaN     NaN     NaN   
7128      NaN  NaN      NaN      NaN   NaN   NaN     NaN     NaN     NaN   
7129      NaN  NaN      NaN      NaN   NaN   NaN     NaN     NaN     NaN   
7130      NaN  NaN      NaN      NaN   NaN   NaN     NaN     NaN     NaN   

      AvgAHA  B365CH  B365CD  B365CA  BWCH  BWCD  BWCA  IWCH  IWCD  IWCA  \
7126     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   
7127     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   
7128     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   
7129     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   
7130     NaN     NaN     NaN     NaN   NaN   NaN   NaN   NaN   NaN   NaN   

      PSCH  PSCD  PSCA  WHCH  WHCD  WHCA  VCCH  VCCD  VCCA  MaxCH  MaxCD  \
7126   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   
7127   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   
7128   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   
7129   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   
7130   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN    NaN    NaN   

      MaxCA  AvgCH  AvgCD  AvgCA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  \
7126    NaN    NaN    NaN    NaN        NaN        NaN     NaN     NaN   
7127    NaN    NaN    NaN    NaN        NaN        NaN     NaN     NaN   
7128    NaN    NaN    NaN    NaN        NaN        NaN     NaN     

#### Coloumns/features in data

In [8]:
df.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'LBAH', 'B365AH', 'SOH', 'SOD', 'SOA', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52'],
      dtype='object', length=156)

#### Length of data

In [9]:
print('lenght of data is', len(df))

lenght of data is 7131


#### Shape of data

In [10]:
df.shape

(7131, 156)

#### Data information

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7131 entries, 0 to 7130
Columns: 156 entries, Div to Unnamed: 52
dtypes: float64(148), object(8)
memory usage: 8.5+ MB


#### Data types of all coloumns

In [12]:
df.dtypes

Div             object
Date            object
Time            object
HomeTeam        object
AwayTeam        object
                ...   
Unnamed: 48    float64
Unnamed: 49    float64
Unnamed: 50    float64
Unnamed: 51    float64
Unnamed: 52    float64
Length: 156, dtype: object

#### Rows and columns in the dataset

In [13]:
print('Count of columns in the data is:  ', len(df.columns))

Count of columns in the data is:   156


In [14]:
print('Count of rows in the data is:  ', len(df))

Count of rows in the data is:   7131


In [15]:
#exporting th dataset to ./data folder in the project for further analysis and visualizations
df.to_csv('df.csv',index=False)

### Data cleaning and subsetting required data
Remove betting data as we don't need it for prediction. Dropping any unnecessary columns as well. 

In [16]:
#we only require the first 22 columns for the purpose of prediction

df_new = df.iloc[:,:23]
df_new = df_new.drop(['Div','Date','Time'],axis=1)

table_features = df.iloc[:,:7]
table_features = table_features.drop(['FTHG','FTAG','Div','Date'],axis=1)

In [17]:
df_new.head()

HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR     Referee  \
0          Fulham      Arsenal   0.0   3.0   A   0.0   1.0   A  C Kavanagh   
1  Crystal Palace  Southampton   1.0   0.0   H   1.0   0.0   H      J Moss   
2       Liverpool        Leeds   4.0   3.0   H   3.0   2.0   H    M Oliver   
3        West Ham    Newcastle   0.0   2.0   A   0.0   0.0   D   S Attwell   
4       West Brom    Leicester   0.0   3.0   A   0.0   0.0   D    A Taylor   

     HS    AS  HST  AST    HF    AF   HC   AC   HY   AY   HR  
0   5.0  13.0  2.0  6.0  12.0  12.0  2.0  3.0  2.0  2.0  0.0  
1   5.0   9.0  3.0  5.0  14.0  11.0  7.0  3.0  2.0  1.0  0.0  
2  22.0   6.0  6.0  3.0   9.0   6.0  9.0  0.0  1.0  0.0  0.0  
3  15.0  15.0  3.0  2.0  13.0   7.0  8.0  7.0  2.0  2.0  0.0  
4   7.0  13.0  1.0  7.0  12.0   9.0  2.0  5.0  1.0  1.0  0.0

In [18]:
df_new.shape[0]

7131

In [19]:
avg_home_scored = df_new.FTHG.sum()*1.0 / df_new.shape[0]
avg_away_scored = df_new.FTAG.sum()*1.0 / df_new.shape[0]

avg_home_conceded = avg_away_scored
avg_away_conceded = avg_home_scored

print("Average number of goals at home =",avg_home_scored)
print("Average number of goals away =", avg_away_scored)
print("Average number of goals conceded at home =",avg_home_conceded)
print("Average number of goals conceded away",avg_away_conceded)

Average number of goals at home = 1.5201234048520544
Average number of goals away = 1.1531342027766092
Average number of goals conceded at home = 1.1531342027766092
Average number of goals conceded away 1.5201234048520544


Creating 2 groupby objects - one for Home Teams and the other for Away Teams.

In [20]:
result_home = df_new.groupby(['HomeTeam'])
result_away = df_new.groupby('AwayTeam')

>Some Terminology fot understanding purpose:

HGS - Home Goals Scored

AGC - Away Goals Scored

HGC - Home Goals Conceded

AGC - Away Goals Conceded

>Goals Scored:
>>HGS = Full-Time Goal Scored (home) / Total Home Games Played 

>>AGC = Full-Time Goal Scored (away) / Total Away Games Played


>Goals Conceded
>>HGC = Full-Time Goal Conceded (home) / Total Home Games Played

>>AGC = Full-Time Goal Conceded (away) / Total Away Games Played

In [21]:
table = pd.DataFrame()

table['HGS'] = result_home['FTHG'].sum()
table['HGC'] = result_home['FTAG'].sum()
table['AGS'] = result_away['FTAG'].sum()
table['AGC'] = result_away['FTHG'].sum()

table.head()

HGS    HGC    AGS    AGC
HomeTeam                               
Arsenal      748.0  308.0  584.0  440.0
Aston Villa  373.0  353.0  339.0  495.0
Birmingham   157.0  136.0  107.0  213.0
Blackburn    252.0  213.0  201.0  312.0
Blackpool     30.0   37.0   25.0   41.0

In [22]:
table.reset_index(inplace=True)
table.head()

HomeTeam    HGS    HGC    AGS    AGC
0      Arsenal  748.0  308.0  584.0  440.0
1  Aston Villa  373.0  353.0  339.0  495.0
2   Birmingham  157.0  136.0  107.0  213.0
3    Blackburn  252.0  213.0  201.0  312.0
4    Blackpool   30.0   37.0   25.0   41.0

In [23]:
#renaming the columns

table.columns.values[0] = "Team"
table.head()

Team    HGS    HGC    AGS    AGC
0      Arsenal  748.0  308.0  584.0  440.0
1  Aston Villa  373.0  353.0  339.0  495.0
2   Birmingham  157.0  136.0  107.0  213.0
3    Blackburn  252.0  213.0  201.0  312.0
4    Blackpool   30.0   37.0   25.0   41.0

>Some Terminology for understanding purpose:

HAS - Home Attack Score

AAS - Away Attack Score
 
HDS - Home Defense Score

ADS - Away Defense Score

> Attack Score = Average Goals Scored / League Average Goal Scored

> Defense Score = Average Goals Conceded / League Average Goal Conceded

In [24]:
#Assuming number of home games = number of away games
num_games = df_new.shape[0]/40

In [25]:
#Home/Away Attack & Defense Score

table['HAS'] = (table['HGS'] / num_games) / avg_home_scored
table['AAS'] = (table['AGS'] / num_games) / avg_away_scored
table['HDS'] = (table['HGC'] / num_games) / avg_home_conceded
table['ADS'] = (table['AGC'] / num_games) / avg_away_conceded
table.head()

Team    HGS    HGC    AGS    AGC       HAS       AAS       HDS  \
0      Arsenal  748.0  308.0  584.0  440.0  2.760148  2.840812  1.498237   
1  Aston Villa  373.0  353.0  339.0  495.0  1.376384  1.649033  1.717135   
2   Birmingham  157.0  136.0  107.0  213.0  0.579336  0.520491  0.661559   
3    Blackburn  252.0  213.0  201.0  312.0  0.929889  0.977745  1.036118   
4    Blackpool   30.0   37.0   25.0   41.0  0.110701  0.121610  0.179983   

        ADS  
0  1.623616  
1  1.826568  
2  0.785978  
3  1.151292  
4  0.151292

In [26]:
cols = ['HAS', 'AAS', 'HDS', 'ADS']

table[cols] = table[cols].round(3)

table.head()

Team    HGS    HGC    AGS    AGC    HAS    AAS    HDS    ADS
0      Arsenal  748.0  308.0  584.0  440.0  2.760  2.841  1.498  1.624
1  Aston Villa  373.0  353.0  339.0  495.0  1.376  1.649  1.717  1.827
2   Birmingham  157.0  136.0  107.0  213.0  0.579  0.520  0.662  0.786
3    Blackburn  252.0  213.0  201.0  312.0  0.930  0.978  1.036  1.151
4    Blackpool   30.0   37.0   25.0   41.0  0.111  0.122  0.180  0.151

### Working on the feature table

feature_table contains all the fixtures in the current season | 
ftr = full time result | 
hst = home shots on target | 
ast = away shots on target |

To create the feature table which is going to be used for prediction we need to slice some data from the 'df' just created and map the respective home and away team values for Attack and Defense Score respectively.

In [27]:
# slicing first 23 columns from df table for prediction purposes

feature_table = df.iloc[:,:23]

feature_table = feature_table[['HomeTeam','AwayTeam','FTR','HST','AST']]

f_HAS = []
f_HDS = []
f_AAS = []
f_ADS = []
for index,row in feature_table.iterrows():
    f_HAS.append(table[table['Team'] == row['HomeTeam']]['HAS'].values)
    f_HDS.append(table[table['Team'] == row['HomeTeam']]['HDS'].values)
    f_AAS.append(table[table['Team'] == row['AwayTeam']]['AAS'].values)
    f_ADS.append(table[table['Team'] == row['AwayTeam']]['ADS'].values)
    
feature_table['HAS'] = f_HAS
feature_table['HDS'] = f_HDS
feature_table['AAS'] = f_AAS
feature_table['ADS'] = f_ADS
feature_table.head()

HomeTeam     AwayTeam FTR  HST  AST      HAS      HDS      AAS  \
0          Fulham      Arsenal   A  2.0  6.0   [1.28]  [1.649]  [2.841]   
1  Crystal Palace  Southampton   H  3.0  5.0  [0.675]  [1.056]  [1.124]   
2       Liverpool        Leeds   H  6.0  3.0  [2.642]  [1.352]  [0.389]   
3        West Ham    Newcastle   A  3.0  2.0   [1.59]  [2.004]  [1.523]   
4       West Brom    Leicester   A  1.0  7.0  [1.077]  [1.741]   [1.06]   

       ADS  
0  [1.624]  
1  [1.251]  
2  [0.387]  
3  [1.959]  
4  [0.845]

In [28]:
#method to convert the datatype of certain colummns

from array import *
def conversion(array_array,col_name):
    list_array = array_array.tolist()
    list_list = []
    for arr in list_array:
        lst = arr.tolist()
        list_list.append(lst)
    df_col = pd.DataFrame(list_list, columns = [col_name])
    return df_col

In [29]:
df_has = conversion(feature_table["HAS"], "has")
df_hds = conversion(feature_table["HDS"], "hds")
df_aas = conversion(feature_table["AAS"], "aas")
df_ads = conversion(feature_table["ADS"], "ads")

In [30]:
final_table = feature_table.join([df_has,df_hds,df_aas,df_ads])

In [31]:
final_table.drop(columns=["HAS","HDS","AAS","ADS"],inplace=True)

In [32]:
final_table

HomeTeam     AwayTeam FTR  HST   AST    has    hds    aas    ads
0             Fulham      Arsenal   A  2.0   6.0  1.280  1.649  2.841  1.624
1     Crystal Palace  Southampton   H  3.0   5.0  0.675  1.056  1.124  1.251
2          Liverpool        Leeds   H  6.0   3.0  2.642  1.352  0.389  0.387
3           West Ham    Newcastle   A  3.0   2.0  1.590  2.004  1.523  1.959
4          West Brom    Leicester   A  1.0   7.0  1.077  1.741  1.060  0.845
...              ...          ...  ..  ...   ...    ...    ...    ...    ...
7126           Leeds  Aston Villa   H  5.0   6.0  0.273  0.365  1.649  1.827
7127        Man City  Southampton   A  7.0   3.0  2.786  1.508  1.124  1.251
7128      Sunderland      Arsenal   A  3.0  13.0  0.908  1.479  2.841  1.624
7129       Tottenham    Blackburn   A  7.0   9.0  2.402  1.766  0.978  1.151
7130       West Brom    Newcastle   D  3.0   9.0  1.077  1.741  1.523  1.959

[7131 rows x 9 columns]

In [33]:
final_table.rename(columns = {'has':'HAS', 'hds':'HDS','aas':'AAS', 'ads':'ADS'}, inplace = True)

In [34]:
final_table

HomeTeam     AwayTeam FTR  HST   AST    HAS    HDS    AAS    ADS
0             Fulham      Arsenal   A  2.0   6.0  1.280  1.649  2.841  1.624
1     Crystal Palace  Southampton   H  3.0   5.0  0.675  1.056  1.124  1.251
2          Liverpool        Leeds   H  6.0   3.0  2.642  1.352  0.389  0.387
3           West Ham    Newcastle   A  3.0   2.0  1.590  2.004  1.523  1.959
4          West Brom    Leicester   A  1.0   7.0  1.077  1.741  1.060  0.845
...              ...          ...  ..  ...   ...    ...    ...    ...    ...
7126           Leeds  Aston Villa   H  5.0   6.0  0.273  0.365  1.649  1.827
7127        Man City  Southampton   A  7.0   3.0  2.786  1.508  1.124  1.251
7128      Sunderland      Arsenal   A  3.0  13.0  0.908  1.479  2.841  1.624
7129       Tottenham    Blackburn   A  7.0   9.0  2.402  1.766  0.978  1.151
7130       West Brom    Newcastle   D  3.0   9.0  1.077  1.741  1.523  1.959

[7131 rows x 9 columns]

In [35]:
#Converts FTR - Full Time Results (Home,Away or Draw) into numeric values

def transformResult(row):
    if(row.FTR == 'H'):
        return 1
    elif(row.FTR == 'A'):
        return -1
    else:
        return 0

In [36]:
final_table["Result"] = final_table.apply(lambda row: transformResult(row),axis=1)
final_table.head()

HomeTeam     AwayTeam FTR  HST  AST    HAS    HDS    AAS    ADS  \
0          Fulham      Arsenal   A  2.0  6.0  1.280  1.649  2.841  1.624   
1  Crystal Palace  Southampton   H  3.0  5.0  0.675  1.056  1.124  1.251   
2       Liverpool        Leeds   H  6.0  3.0  2.642  1.352  0.389  0.387   
3        West Ham    Newcastle   A  3.0  2.0  1.590  2.004  1.523  1.959   
4       West Brom    Leicester   A  1.0  7.0  1.077  1.741  1.060  0.845   

   Result  
0      -1  
1       1  
2       1  
3      -1  
4      -1

In [37]:
#exporting final_table to ./data folder of the project

final_table.to_csv('final_table.csv',index=False)

<div class="alert alert-block alert-info">  
<h2><center><strong>Prediction Model</strong></center></h2>
        
</div>

In [38]:
#dropping 1 row which had null values

final_table.dropna(inplace=True)
final_table

HomeTeam     AwayTeam FTR  HST   AST    HAS    HDS    AAS    ADS  \
0             Fulham      Arsenal   A  2.0   6.0  1.280  1.649  2.841  1.624   
1     Crystal Palace  Southampton   H  3.0   5.0  0.675  1.056  1.124  1.251   
2          Liverpool        Leeds   H  6.0   3.0  2.642  1.352  0.389  0.387   
3           West Ham    Newcastle   A  3.0   2.0  1.590  2.004  1.523  1.959   
4          West Brom    Leicester   A  1.0   7.0  1.077  1.741  1.060  0.845   
...              ...          ...  ..  ...   ...    ...    ...    ...    ...   
7126           Leeds  Aston Villa   H  5.0   6.0  0.273  0.365  1.649  1.827   
7127        Man City  Southampton   A  7.0   3.0  2.786  1.508  1.124  1.251   
7128      Sunderland      Arsenal   A  3.0  13.0  0.908  1.479  2.841  1.624   
7129       Tottenham    Blackburn   A  7.0   9.0  2.402  1.766  0.978  1.151   
7130       West Brom    Newcastle   D  3.0   9.0  1.077  1.741  1.523  1.959   

      Result  
0         -1  
1          1  
2          1  
3         -1  
4         -1  
...      ...  
7126       1  
7127      -1  
7128      -1  
7129      -1  
7130       0  

[7130 rows x 10 columns]

In [39]:
final_table.isnull().values.any()

False

In [40]:
#splitting the data into independent and dependent variables

X_train = final_table[['HST','AST','HAS','HDS','AAS','ADS',]]
y_train = final_table['Result']

In [41]:
X_train,test_X,y_train,test_y=train_test_split(X_train,y_train,random_state=0)

We are evaluating 3 focused models to check which one is providing the most accurate result. Logistic Regression, Linear SVC and KNeighborsClassifier.

> <h2><b>Logistic Regression<b></h2>

In [42]:
model1 = LogisticRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.fit(X_train,y_train).predict(X_train)
y_pred1

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [43]:
ac1=accuracy_score(y_pred1,y_train)
accuracy_score(y_pred1,y_train)

0.5679820460071068

> <h2><b>KNN<b></h2>

In [44]:
model2 = KNeighborsClassifier()
model2.fit(X_train, y_train)
y_pred2 = model2.fit(X_train,y_train).predict(X_train)
y_pred2

array([-1, -1,  1, ...,  1, -1,  1], dtype=int64)

In [45]:
ac2=accuracy_score(y_pred2,y_train)
accuracy_score(y_pred2,y_train)

0.6484009725079484

> <h2><b>SVC<b></h2>

In [46]:
model3 =  LinearSVC()
y_pred3 = model3.fit(X_train, y_train).predict(X_train)
y_pred3

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [47]:
ac3=accuracy_score(y_pred3,y_train)
accuracy_score(y_pred3,y_train)

0.5679820460071068

> <h2><b>Decision Trees<b></h2>

In [48]:
model4 =  DecisionTreeClassifier()
y_pred4 = model4.fit(X_train, y_train).predict(X_train)
y_pred4

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [49]:
ac4=accuracy_score(y_pred4,y_train)
accuracy_score(y_pred4,y_train)

0.9820460071067888

> <h2><b>Naive Bayes<b></h2>

In [50]:
model5 =  GaussianNB()
y_pred5 = model5.fit(X_train, y_train).predict(X_train)
y_pred5

array([-1, -1,  1, ...,  1,  1,  1], dtype=int64)

In [51]:
ac5=accuracy_score(y_pred5,y_train)
accuracy_score(y_pred5,y_train)

0.5509631569104171

> <h2><b>Linear Discriminant Analysis<b></h2>

In [52]:
model6 =  LinearDiscriminantAnalysis()
y_pred6 = model6.fit(X_train, y_train).predict(X_train)
y_pred6

array([-1,  1,  1, ...,  1,  1,  1], dtype=int64)

In [53]:
ac6=accuracy_score(y_pred6,y_train)
accuracy_score(y_pred6,y_train)

0.5666729006919768

> <h2><b>AdaBoost Classifier<b></h2>

In [54]:
model7 =  AdaBoostClassifier()
y_pred7 = model7.fit(X_train, y_train).predict(X_train)
y_pred7

array([-1,  1,  1, ...,  1,  1,  1], dtype=int64)

In [55]:
ac7=accuracy_score(y_pred7,y_train)
accuracy_score(y_pred7,y_train)

0.5821956237142323

> <h2><b>Random Forest<b></h2>

In [56]:
model8 =  RandomForestClassifier()
y_pred8 = model8.fit(X_train, y_train).predict(X_train)
y_pred8

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [57]:
ac8=accuracy_score(y_pred8,y_train)
accuracy_score(y_pred8,y_train)

0.9820460071067888

> <h2><b>Extra Trees Classifier<b></h2>

In [58]:
model9 =  ExtraTreesClassifier()
y_pred9 = model9.fit(X_train, y_train).predict(X_train)
y_pred9

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [59]:
ac9=accuracy_score(y_pred9,y_train)
accuracy_score(y_pred9,y_train)

0.9820460071067888

> <h2><b>Bagging Classifier<b></h2>

In [60]:
model10 =  BaggingClassifier()
y_pred10 = model10.fit(X_train, y_train).predict(X_train)
y_pred10

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [61]:
ac10=accuracy_score(y_pred10,y_train)
accuracy_score(y_pred10,y_train)

0.9612867028240135

> <h2><b>Gradient Boosting Classifier<b></h2>

In [62]:
model11 =  GradientBoostingClassifier()
y_pred11 = model11.fit(X_train, y_train).predict(X_train)
y_pred11

array([-1,  1,  1, ...,  1, -1,  1], dtype=int64)

In [63]:
ac11=accuracy_score(y_pred11,y_train)
accuracy_score(y_pred11,y_train)

0.6066953431830934

<div class="alert alert-block alert-success">  
<h4>Models Performance Comparison</h4>
        
</div>

In [64]:
x = PrettyTable()
print('\n')
x.field_names = ["Model", "Recall Metric"]

x.add_row(["Logistic Regression", round(ac1,4)])
x.add_row(["KNN", round(ac2,4)])
x.add_row(["SVC", round(ac3,4)])
x.add_row(["Decision Trees", round(ac4,4)])
x.add_row(["Naive Bayes", round(ac5,4)])
x.add_row(["Linear Discriminant Analysis", round(ac6,4)])
x.add_row(["AdaBoost", round(ac7,4)])
x.add_row(["Random Forest", round(ac8,4)])
x.add_row(["Extra Tree", round(ac9,4)])
x.add_row(["Bagging Clasifier", round(ac10,4)])
x.add_row(["Gradient Boosting Classifier", round(ac11,4)])

print(x)
print('\n')



+------------------------------+---------------+
|            Model             | Recall Metric |
+------------------------------+---------------+
|     Logistic Regression      |     0.568     |
|             KNN              |     0.6484    |
|             SVC              |     0.568     |
|        Decision Trees        |     0.982     |
|         Naive Bayes          |     0.551     |
| Linear Discriminant Analysis |     0.5667    |
|           AdaBoost           |     0.5822    |
|        Random Forest         |     0.982     |
|          Extra Tree          |     0.982     |
|      Bagging Clasifier       |     0.9613    |
| Gradient Boosting Classifier |     0.6067    |
+------------------------------+---------------+




As we can see, Decision Trees, Random Forest and Extra Trees gives us an accuracy score of 98% which is better as compared. SO Random Forest will be used for prediction of the matches in the upcoming week.

<div class="alert alert-block alert-info">  
<h2>Predicting Recent Performance (Upcoming Week Matches)</h2>
        
</div>

In [65]:
#dropping certain columns not needed for recent performance prediction purposes

pred_table = final_table.drop(['HST','AST'],axis=1)
pred_table

HomeTeam     AwayTeam FTR    HAS    HDS    AAS    ADS  Result
0             Fulham      Arsenal   A  1.280  1.649  2.841  1.624      -1
1     Crystal Palace  Southampton   H  0.675  1.056  1.124  1.251       1
2          Liverpool        Leeds   H  2.642  1.352  0.389  0.387       1
3           West Ham    Newcastle   A  1.590  2.004  1.523  1.959      -1
4          West Brom    Leicester   A  1.077  1.741  1.060  0.845      -1
...              ...          ...  ..    ...    ...    ...    ...     ...
7126           Leeds  Aston Villa   H  0.273  0.365  1.649  1.827       1
7127        Man City  Southampton   A  2.786  1.508  1.124  1.251      -1
7128      Sunderland      Arsenal   A  0.908  1.479  2.841  1.624      -1
7129       Tottenham    Blackburn   A  2.402  1.766  0.978  1.151      -1
7130       West Brom    Newcastle   D  1.077  1.741  1.523  1.959       0

[7130 rows x 8 columns]

In [66]:
# Adding next week fixtures from the website, understat.com

new_fixtures = pd.DataFrame( [['Crystal Palace','Leeds','D',0,0,0,0,0],
                             ['West Ham','Arsenal','D',0,0,0,0,0],
                             ['Everton','Chelsea','D',0,0,0,0,0],
                             ['Newcastle','Liverpool','D',0,0,0,0,0],
                             ['Wolves','Brighton','D',0,0,0,0,0],
                             ['Watford','Burnley','D',0,0,0,0,0],
                             ['Tottenham','Leicester','D',0,0,0,0,0],
                             ['Southampton','Crystal Palace','D',0,0,0,0,0],
                             ['Aston Villa','Norwich','D',0,0,0,0,0],
                             ['Leeds','Man City','D',0,0,0,0,0]],columns=['HomeTeam','AwayTeam', 'FTR',
                                                                            'HAS','HDS','AAS','ADS','Result'])

In [67]:
new_fixtures.head()

HomeTeam   AwayTeam FTR  HAS  HDS  AAS  ADS  Result
0  Crystal Palace      Leeds   D    0    0    0    0       0
1        West Ham    Arsenal   D    0    0    0    0       0
2         Everton    Chelsea   D    0    0    0    0       0
3       Newcastle  Liverpool   D    0    0    0    0       0
4          Wolves   Brighton   D    0    0    0    0       0

In [68]:
#Mapping the Home and Away - Attack and Defense Score from the 'table' df

new_HAS = []
new_HDS = []
new_AAS = []
new_ADS = []
for index,row in new_fixtures.iterrows():
    new_HAS.append(table[table['Team'] == row['HomeTeam']]['HAS'].values[0])
    new_HDS.append(table[table['Team'] == row['HomeTeam']]['HDS'].values[0])
    new_AAS.append(table[table['Team'] == row['AwayTeam']]['AAS'].values[0])
    new_ADS.append(table[table['Team'] == row['AwayTeam']]['ADS'].values[0])
    
new_fixtures['HAS'] = new_HAS
new_fixtures['HDS'] = new_HDS
new_fixtures['AAS'] = new_AAS
new_fixtures['ADS'] = new_ADS
new_fixtures

HomeTeam        AwayTeam FTR    HAS    HDS    AAS    ADS  Result
0  Crystal Palace           Leeds   D  0.675  1.056  0.389  0.387       0
1        West Ham         Arsenal   D  1.590  2.004  2.841  1.624       0
2         Everton         Chelsea   D  2.096  1.858  2.778  1.332       0
3       Newcastle       Liverpool   D  1.690  1.917  2.709  1.561       0
4          Wolves        Brighton   D  0.587  0.910  0.306  0.413       0
5         Watford         Burnley   D  0.513  0.773  0.598  0.856       0
6       Tottenham       Leicester   D  2.402  1.766  1.060  0.845       0
7     Southampton  Crystal Palace   D  1.173  1.333  0.924  1.026       0
8     Aston Villa         Norwich   D  1.376  1.717  0.394  0.841       0
9           Leeds        Man City   D  0.273  0.365  2.758  1.601       0

In [69]:
#Taking the training features from the pred_table created earlier
#Independent variables - HAS, HDS, AAS, ADS
#Dependent variable - Result

train_x = pred_table[['HAS','HDS','AAS','ADS']]
train_y = pred_table['Result']

In [70]:
#using the upcoming week data as test data

X_test = new_fixtures[['HAS','HDS','AAS','ADS']]
y_test = new_fixtures['Result']

In [71]:
clf = RandomForestClassifier()
model = clf.fit(train_x,train_y)
pred = clf.predict(X_test)

In [72]:
pred

array([ 1, -1, -1,  1,  0, -1,  1,  1,  1,  1], dtype=int64)

In [73]:
this_week = new_fixtures[['HomeTeam','AwayTeam']]
this_week['Result']=pred
this_week

HomeTeam        AwayTeam  Result
0  Crystal Palace           Leeds       1
1        West Ham         Arsenal      -1
2         Everton         Chelsea      -1
3       Newcastle       Liverpool       1
4          Wolves        Brighton       0
5         Watford         Burnley      -1
6       Tottenham       Leicester       1
7     Southampton  Crystal Palace       1
8     Aston Villa         Norwich       1
9           Leeds        Man City       1

In [74]:
def transformResultBack(row,col_name):
    if(row[col_name] == 1):
        return 'H'
    elif(row[col_name] == -1):
        return 'A'
    else:
        return 'D'

In [75]:
this_week["Full Time Result"] = this_week.apply(lambda row: transformResultBack(row,"Result"),axis=1)

this_week.drop(["Result"],axis=1,inplace=True)
this_week

HomeTeam        AwayTeam Full Time Result
0  Crystal Palace           Leeds                H
1        West Ham         Arsenal                A
2         Everton         Chelsea                A
3       Newcastle       Liverpool                H
4          Wolves        Brighton                D
5         Watford         Burnley                A
6       Tottenham       Leicester                H
7     Southampton  Crystal Palace                H
8     Aston Villa         Norwich                H
9           Leeds        Man City                H

In [76]:
this_week.to_csv('this_week.csv',index=False)

<div class="alert alert-block alert-info">  
<h2>Analysis of Football season and team stats</h2>
        
</div>

In [77]:
# load the csv file created after scraping the data from 'data' folder of the project
import pandas as pd

df = pd.read_csv('df.csv')
df.head()

Div        Date   Time        HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0  12/09/2020  12:30          Fulham      Arsenal   0.0   3.0   A   0.0   
1  E0  12/09/2020  15:00  Crystal Palace  Southampton   1.0   0.0   H   1.0   
2  E0  12/09/2020  17:30       Liverpool        Leeds   4.0   3.0   H   3.0   
3  E0  12/09/2020  20:00        West Ham    Newcastle   0.0   2.0   A   0.0   
4  E0  13/09/2020  14:00       West Brom    Leicester   0.0   3.0   A   0.0   

   HTAG HTR     Referee    HS    AS  HST  AST    HF    AF   HC   AC   HY   AY  \
0   1.0   A  C Kavanagh   5.0  13.0  2.0  6.0  12.0  12.0  2.0  3.0  2.0  2.0   
1   0.0   H      J Moss   5.0   9.0  3.0  5.0  14.0  11.0  7.0  3.0  2.0  1.0   
2   2.0   H    M Oliver  22.0   6.0  6.0  3.0   9.0   6.0  9.0  0.0  1.0  0.0   
3   0.0   D   S Attwell  15.0  15.0  3.0  2.0  13.0   7.0  8.0  7.0  2.0  2.0   
4   0.0   D    A Taylor   7.0  13.0  1.0  7.0  12.0   9.0  2.0  5.0  1.0  1.0   

    HR   AR  B365H  B365D  B365A   BWH   BWD    BWA   IWH   IWD   IWA   PSH  \
0  0.0  0.0   6.00   4.33   1.53  5.50  4.25   1.57  6.00  3.90  1.57  6.16   
1  0.0  0.0   3.10   3.25   2.37  3.00  3.20   2.45  3.15  2.95  2.40  3.32   
2  0.0  0.0   1.28   6.00   9.50  1.26  6.25  10.50  1.35  5.00  8.50  1.31   
3  0.0  0.0   2.15   3.40   3.40  2.15  3.40   3.40  2.15  3.15  3.40  2.18   
4  0.0  0.0   3.80   3.60   1.95  3.70  3.60   2.00  3.85  3.20  2.00  4.00   

    PSD   PSA   WHH  WHD    WHA   VCH   VCD    VCA  MaxH  MaxD   MaxA  AvgH  \
0  4.51  1.56  6.50  4.2   1.53  6.50  4.20   1.55  6.55  4.55   1.60  5.94   
1  3.29  2.40  3.20  3.2   2.35  3.20  3.20   2.40  3.36  3.36   2.50  3.18   
2  6.25  9.92  1.27  6.0  10.00  1.30  5.75  10.50  1.35  6.50  10.75  1.30   
3  3.61  3.50  2.15  3.5   3.40  2.15  3.40   3.60  2.24  3.70   3.60  2.15   
4  3.59  2.00  3.80  3.6   1.95  4.00  3.50   1.95  4.00  3.82   2.04  3.87   

   AvgD  AvgA  B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  \
0  4.34  1.55      1.72      2.10   1.80   2.13     1.84     2.18     1.76   
1  3.22  2.39      2.20      1.66   2.34   1.68     2.36     1.73     2.24   
2  5.96  9.68      1.53      2.50   1.56   2.60     1.56     2.68     1.52   
3  3.48  3.42      1.90      1.90   2.00   1.91     2.05     1.95     1.97   
4  3.57  1.97      1.90      1.90   2.00   1.91     2.02     2.03     1.92   

   Avg<2.5   AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  \
0     2.10  1.00     1.93     1.97  1.96  1.96    2.00    1.99    1.93   
1     1.67  0.25     1.85     2.05  1.88  2.05    1.88    2.07    1.84   
2     2.53 -1.50     1.95     1.95  1.97  1.95    2.00    2.08    1.90   
3     1.86 -0.50     2.07     1.72  2.17  1.78    2.17    1.81    2.12   
4     1.90  0.50     1.91     1.99  1.92  2.00    1.93    2.02    1.88   

   AvgAHA  B365CH  B365CD  B365CA  BWCH  BWCD   BWCA  IWCH  IWCD  IWCA  PSCH  \
0    1.95    5.00    4.00    1.66  5.50  4.00   1.62  5.25  3.90  1.67  5.48   
1    2.03    3.00    3.25    2.40  3.00  3.30   2.40  3.05  2.90  2.45  3.09   
2    1.97    1.25    6.00   11.00  1.25  6.25  11.00  1.30  6.00  9.00  1.28   
3    1.75    1.95    3.60    3.75  1.95  3.70   3.75  2.05  3.25  3.75  2.04   
4    1.97    3.25    3.40    2.20  3.30  3.40   2.20  3.35  3.00  2.30  3.38   

   PSCD   PSCA  WHCH  WHCD   WHCA  VCCH  VCCD   VCCA  MaxCH  MaxCD  MaxCA  \
0  3.98   1.69  5.50   3.8   1.65  5.50  3.90   1.67   5.75   4.20   1.71   
1  3.27   2.54  3.10   3.1   2.45  3.10  3.25   2.45   3.25   3.33   2.55   
2  6.34  11.38  1.25   6.0  12.00  1.29  6.00  11.50   1.30   6.75  12.27   
3  3.59   3.92  2.00   3.5   3.80  2.00  3.50   3.90   2.07   3.78   3.99   
4  3.38   2.32  3.30   3.3   2.25  3.30  3.30   2.30   3.55   3.50   2.38   

   AvgCH  AvgCD  AvgCA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  \
0   5.36   3.93   1.67        2.0       1.80    2.06    1.86      2.10   
1   3.08   3.22   2.47        2.2       1.66    2.26    1.72      2.27   
2   1.28  

In [78]:
def change_into_datetime(col):
    df[col]=pd.to_datetime(df[col])
change_into_datetime("Date")
df.head()

Div       Date   Time        HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0  E0 2020-12-09  12:30          Fulham      Arsenal   0.0   3.0   A   0.0   
1  E0 2020-12-09  15:00  Crystal Palace  Southampton   1.0   0.0   H   1.0   
2  E0 2020-12-09  17:30       Liverpool        Leeds   4.0   3.0   H   3.0   
3  E0 2020-12-09  20:00        West Ham    Newcastle   0.0   2.0   A   0.0   
4  E0 2020-09-13  14:00       West Brom    Leicester   0.0   3.0   A   0.0   

   HTAG HTR     Referee    HS    AS  HST  AST    HF    AF   HC   AC   HY   AY  \
0   1.0   A  C Kavanagh   5.0  13.0  2.0  6.0  12.0  12.0  2.0  3.0  2.0  2.0   
1   0.0   H      J Moss   5.0   9.0  3.0  5.0  14.0  11.0  7.0  3.0  2.0  1.0   
2   2.0   H    M Oliver  22.0   6.0  6.0  3.0   9.0   6.0  9.0  0.0  1.0  0.0   
3   0.0   D   S Attwell  15.0  15.0  3.0  2.0  13.0   7.0  8.0  7.0  2.0  2.0   
4   0.0   D    A Taylor   7.0  13.0  1.0  7.0  12.0   9.0  2.0  5.0  1.0  1.0   

    HR   AR  B365H  B365D  B365A   BWH   BWD    BWA   IWH   IWD   IWA   PSH  \
0  0.0  0.0   6.00   4.33   1.53  5.50  4.25   1.57  6.00  3.90  1.57  6.16   
1  0.0  0.0   3.10   3.25   2.37  3.00  3.20   2.45  3.15  2.95  2.40  3.32   
2  0.0  0.0   1.28   6.00   9.50  1.26  6.25  10.50  1.35  5.00  8.50  1.31   
3  0.0  0.0   2.15   3.40   3.40  2.15  3.40   3.40  2.15  3.15  3.40  2.18   
4  0.0  0.0   3.80   3.60   1.95  3.70  3.60   2.00  3.85  3.20  2.00  4.00   

    PSD   PSA   WHH  WHD    WHA   VCH   VCD    VCA  MaxH  MaxD   MaxA  AvgH  \
0  4.51  1.56  6.50  4.2   1.53  6.50  4.20   1.55  6.55  4.55   1.60  5.94   
1  3.29  2.40  3.20  3.2   2.35  3.20  3.20   2.40  3.36  3.36   2.50  3.18   
2  6.25  9.92  1.27  6.0  10.00  1.30  5.75  10.50  1.35  6.50  10.75  1.30   
3  3.61  3.50  2.15  3.5   3.40  2.15  3.40   3.60  2.24  3.70   3.60  2.15   
4  3.59  2.00  3.80  3.6   1.95  4.00  3.50   1.95  4.00  3.82   2.04  3.87   

   AvgD  AvgA  B365>2.5  B365<2.5  P>2.5  P<2.5  Max>2.5  Max<2.5  Avg>2.5  \
0  4.34  1.55      1.72      2.10   1.80   2.13     1.84     2.18     1.76   
1  3.22  2.39      2.20      1.66   2.34   1.68     2.36     1.73     2.24   
2  5.96  9.68      1.53      2.50   1.56   2.60     1.56     2.68     1.52   
3  3.48  3.42      1.90      1.90   2.00   1.91     2.05     1.95     1.97   
4  3.57  1.97      1.90      1.90   2.00   1.91     2.02     2.03     1.92   

   Avg<2.5   AHh  B365AHH  B365AHA  PAHH  PAHA  MaxAHH  MaxAHA  AvgAHH  \
0     2.10  1.00     1.93     1.97  1.96  1.96    2.00    1.99    1.93   
1     1.67  0.25     1.85     2.05  1.88  2.05    1.88    2.07    1.84   
2     2.53 -1.50     1.95     1.95  1.97  1.95    2.00    2.08    1.90   
3     1.86 -0.50     2.07     1.72  2.17  1.78    2.17    1.81    2.12   
4     1.90  0.50     1.91     1.99  1.92  2.00    1.93    2.02    1.88   

   AvgAHA  B365CH  B365CD  B365CA  BWCH  BWCD   BWCA  IWCH  IWCD  IWCA  PSCH  \
0    1.95    5.00    4.00    1.66  5.50  4.00   1.62  5.25  3.90  1.67  5.48   
1    2.03    3.00    3.25    2.40  3.00  3.30   2.40  3.05  2.90  2.45  3.09   
2    1.97    1.25    6.00   11.00  1.25  6.25  11.00  1.30  6.00  9.00  1.28   
3    1.75    1.95    3.60    3.75  1.95  3.70   3.75  2.05  3.25  3.75  2.04   
4    1.97    3.25    3.40    2.20  3.30  3.40   2.20  3.35  3.00  2.30  3.38   

   PSCD   PSCA  WHCH  WHCD   WHCA  VCCH  VCCD   VCCA  MaxCH  MaxCD  MaxCA  \
0  3.98   1.69  5.50   3.8   1.65  5.50  3.90   1.67   5.75   4.20   1.71   
1  3.27   2.54  3.10   3.1   2.45  3.10  3.25   2.45   3.25   3.33   2.55   
2  6.34  11.38  1.25   6.0  12.00  1.29  6.00  11.50   1.30   6.75  12.27   
3  3.59   3.92  2.00   3.5   3.80  2.00  3.50   3.90   2.07   3.78   3.99   
4  3.38   2.32  3.30   3.3   2.25  3.30  3.30   2.30   3.55   3.50   2.38   

   AvgCH  AvgCD  AvgCA  B365C>2.5  B365C<2.5  PC>2.5  PC<2.5  MaxC>2.5  \
0   5.36   3.93   1.67        2.0       1.80    2.06    1.86      2.10   
1   3.08   3.22   2.47        2.2       1.66    2.26    1.72      2.27   
2   1.28   6.16 

In [79]:
#removing betting data columns from original df
#removing 21-22 season as it is incomplete and not suitable for further analysis

df_complete = df.iloc[323: , :24] 
df_complete = df_complete.sort_index(ascending=False)

df_complete =df_complete.drop(['Div','Time'],axis=1)
df_complete.head()

Date    HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  HTAG HTR  \
7130 2003-11-05   West Brom    Newcastle   2.0   2.0   D   0.0   1.0   A   
7129 2003-11-05   Tottenham    Blackburn   0.0   4.0   A   0.0   2.0   A   
7128 2003-11-05  Sunderland      Arsenal   0.0   4.0   A   0.0   2.0   A   
7127 2003-11-05    Man City  Southampton   0.0   1.0   A   0.0   1.0   A   
7126 2003-11-05       Leeds  Aston Villa   3.0   1.0   H   1.0   1.0   D   

       Referee    HS    AS  HST   AST    HF    AF    HC    AC   HY   AY   HR  \
7130  G Barber   8.0  14.0  3.0   9.0   9.0   8.0   2.0   8.0  0.0  0.0  0.0   
7129  A D'Urso  11.0  13.0  7.0   9.0   9.0  12.0   6.0   3.0  1.0  1.0  1.0   
7128  P Durkin   7.0  20.0  3.0  13.0  16.0  12.0   6.0  10.0  1.0  0.0  0.0   
7127    M Dean  17.0   6.0  7.0   3.0  14.0  14.0  10.0   4.0  3.0  4.0  0.0   
7126  M Halsey  11.0  18.0  5.0   6.0  18.0  14.0   1.0   8.0  0.0  1.0  0.0   

       AR  
7130  0.0  
7129  0.0  
7128  0.0  
7127  0.0  
7126  0.0

In [80]:
df_complete = df_complete.dropna()
# df_complete.isnull().sum()
df_complete.columns = ['Date','HomeTeam','AwayTeam','H_Goals','A_Goals','FT_Result','H_HT_Goals','A_HT_Goals',
                        'HT_Result','Referee','H_Shots','A_Shots','H_Shots_Target','A_Shots_Target','H_Foul',
                        'A_Foul','H_Corner','A_Corner','H_Yellow','A_Yellow','H_Red','A_Red']

df_complete.head()

Date    HomeTeam     AwayTeam  H_Goals  A_Goals FT_Result  \
7130 2003-11-05   West Brom    Newcastle      2.0      2.0         D   
7129 2003-11-05   Tottenham    Blackburn      0.0      4.0         A   
7128 2003-11-05  Sunderland      Arsenal      0.0      4.0         A   
7127 2003-11-05    Man City  Southampton      0.0      1.0         A   
7126 2003-11-05       Leeds  Aston Villa      3.0      1.0         H   

      H_HT_Goals  A_HT_Goals HT_Result   Referee  H_Shots  A_Shots  \
7130         0.0         1.0         A  G Barber      8.0     14.0   
7129         0.0         2.0         A  A D'Urso     11.0     13.0   
7128         0.0         2.0         A  P Durkin      7.0     20.0   
7127         0.0         1.0         A    M Dean     17.0      6.0   
7126         1.0         1.0         D  M Halsey     11.0     18.0   

      H_Shots_Target  A_Shots_Target  H_Foul  A_Foul  H_Corner  A_Corner  \
7130             3.0             9.0     9.0     8.0       2.0       8.0   
7129             7.0             9.0     9.0    12.0       6.0       3.0   
7128             3.0            13.0    16.0    12.0       6.0      10.0   
7127             7.0             3.0    14.0    14.0      10.0       4.0   
7126             5.0             6.0    18.0    14.0       1.0       8.0   

      H_Yellow  A_Yellow  H_Red  A_Red  
7130       0.0       0.0    0.0    0.0  
7129       1.0       1.0    1.0    0.0  
7128       1.0       0.0    0.0    0.0  
7127       3.0       4.0    0.0    0.0  
7126       0.0       1.0    0.0    0.0

In [81]:
#sorting data according to the Date

df_analysis = df_complete.sort_values(['Date']).reset_index(drop=True)
df_analysis.head()

Date   HomeTeam     AwayTeam  H_Goals  A_Goals FT_Result  H_HT_Goals  \
0 2002-01-09    Chelsea      Arsenal      1.0      1.0         D         1.0   
1 2002-01-09     Bolton  Aston Villa      1.0      0.0         H         0.0   
2 2002-01-12  Newcastle      Everton      2.0      1.0         H         0.0   
3 2002-01-12  Liverpool   Man United      1.0      2.0         A         0.0   
4 2002-01-12      Leeds     Charlton      1.0      2.0         A         1.0   

   A_HT_Goals HT_Result   Referee  H_Shots  A_Shots  H_Shots_Target  \
0         0.0         H  A D'Urso      8.0      8.0             2.0   
1         0.0         D    S Dunn     13.0     12.0             6.0   
2         1.0         A  M Halsey     24.0      7.0            15.0   
3         0.0         D   A Wiley     13.0      5.0             7.0   
4         0.0         H  A D'Urso     18.0     14.0             6.0   

   A_Shots_Target  H_Foul  A_Foul  H_Corner  A_Corner  H_Yellow  A_Yellow  \
0             5.0    20.0    16.0       6.0       2.0       5.0       2.0   
1             5.0     9.0    11.0       4.0       5.0       2.0       3.0   
2             5.0    13.0    18.0      11.0       2.0       0.0       1.0   
3             4.0    13.0    11.0       5.0       2.0       1.0       4.0   
4            10.0    14.0    15.0       5.0      11.0       1.0       1.0   

   H_Red  A_Red  
0    0.0    1.0  
1    0.0    0.0  
2    0.0    1.0  
3    0.0    0.0  
4    0.0    0.0

In [82]:
season_start=2
season_end=3
season_list = []

for x in range (18):
    for y in range (380):
        season_list.append((str(season_start)+'-'+str(season_end)))
    season_start = season_start + 1
    season_end = season_end + 1
season_df = pd.DataFrame({'Season':season_list})

data_by_seasons = pd.concat([season_df,df_analysis], axis=1)
data_by_seasons.head()

Season       Date   HomeTeam     AwayTeam  H_Goals  A_Goals FT_Result  \
0    2-3 2002-01-09    Chelsea      Arsenal      1.0      1.0         D   
1    2-3 2002-01-09     Bolton  Aston Villa      1.0      0.0         H   
2    2-3 2002-01-12  Newcastle      Everton      2.0      1.0         H   
3    2-3 2002-01-12  Liverpool   Man United      1.0      2.0         A   
4    2-3 2002-01-12      Leeds     Charlton      1.0      2.0         A   

   H_HT_Goals  A_HT_Goals HT_Result   Referee  H_Shots  A_Shots  \
0         1.0         0.0         H  A D'Urso      8.0      8.0   
1         0.0         0.0         D    S Dunn     13.0     12.0   
2         0.0         1.0         A  M Halsey     24.0      7.0   
3         0.0         0.0         D   A Wiley     13.0      5.0   
4         1.0         0.0         H  A D'Urso     18.0     14.0   

   H_Shots_Target  A_Shots_Target  H_Foul  A_Foul  H_Corner  A_Corner  \
0             2.0             5.0    20.0    16.0       6.0       2.0   
1             6.0             5.0     9.0    11.0       4.0       5.0   
2            15.0             5.0    13.0    18.0      11.0       2.0   
3             7.0             4.0    13.0    11.0       5.0       2.0   
4             6.0            10.0    14.0    15.0       5.0      11.0   

   H_Yellow  A_Yellow  H_Red  A_Red  
0       5.0       2.0    0.0    1.0  
1       2.0       3.0    0.0    0.0  
2       0.0       1.0    0.0    1.0  
3       1.0       4.0    0.0    0.0  
4       1.0       1.0    0.0    0.0

In [83]:
data_by_seasons = data_by_seasons.dropna()
data_by_seasons.head()

Season       Date   HomeTeam     AwayTeam  H_Goals  A_Goals FT_Result  \
0    2-3 2002-01-09    Chelsea      Arsenal      1.0      1.0         D   
1    2-3 2002-01-09     Bolton  Aston Villa      1.0      0.0         H   
2    2-3 2002-01-12  Newcastle      Everton      2.0      1.0         H   
3    2-3 2002-01-12  Liverpool   Man United      1.0      2.0         A   
4    2-3 2002-01-12      Leeds     Charlton      1.0      2.0         A   

   H_HT_Goals  A_HT_Goals HT_Result   Referee  H_Shots  A_Shots  \
0         1.0         0.0         H  A D'Urso      8.0      8.0   
1         0.0         0.0         D    S Dunn     13.0     12.0   
2         0.0         1.0         A  M Halsey     24.0      7.0   
3         0.0         0.0         D   A Wiley     13.0      5.0   
4         1.0         0.0         H  A D'Urso     18.0     14.0   

   H_Shots_Target  A_Shots_Target  H_Foul  A_Foul  H_Corner  A_Corner  \
0             2.0             5.0    20.0    16.0       6.0       2.0   
1             6.0             5.0     9.0    11.0       4.0       5.0   
2            15.0             5.0    13.0    18.0      11.0       2.0   
3             7.0             4.0    13.0    11.0       5.0       2.0   
4             6.0            10.0    14.0    15.0       5.0      11.0   

   H_Yellow  A_Yellow  H_Red  A_Red  
0       5.0       2.0    0.0    1.0  
1       2.0       3.0    0.0    0.0  
2       0.0       1.0    0.0    1.0  
3       1.0       4.0    0.0    0.0  
4       1.0       1.0    0.0    0.0

In [84]:
delta_names = ['Goals','HT_Goals','Shots_Target','Foul','Corner','Yellow','Red']

for column in delta_names:
    h_delta_column = 'H_Delta_'+ column
    a_delta_column = 'A_Delta_'+ column
    
    h_column = 'H_'+ column
    a_column = 'A_'+ column

    data_by_seasons[h_delta_column] = data_by_seasons[h_column]-data_by_seasons[a_column]
    data_by_seasons[a_delta_column] = data_by_seasons[a_column]-data_by_seasons[h_column]
    
column_names = ['Delta_Goals','Delta_HT_Goals','Delta_Shots_Target','Delta_Foul','Delta_Corner','Delta_Yellow','Delta_Red']

h_column_names = ['Season','HomeTeam','H_Goals','A_Goals','FT_Result','H_HT_Goals','A_HT_Goals','HT_Result','H_Shots_Target','A_Shots_Target','H_Foul','A_Foul','H_Corner','A_Corner','H_Yellow','A_Yellow','H_Red','A_Red']

a_column_names = ['Season','AwayTeam','A_Goals','H_Goals','FT_Result','A_HT_Goals','A_HT_Goals','HT_Result','A_Shots_Target','H_Shots_Target','A_Foul','H_Foul','A_Corner','H_Corner','A_Yellow','H_Yellow','A_Red','H_Red']


column_names_new = ['Season','Team','Goals','Goals_Received','FT_Result','HT_Goals','HT_Goals_Received','HT_Result','Shots_Target','Shots_Target_Received','Fouls','Got_Fouled','Corner','Corner_Received','Yellow','Yellow_Received','Red','Red_Received','Delta_Goals','Delta_HT_Goals','Delta_Shots_On_Target','Delta_Foul','Delta_Corner','Delta_Yellow','Delta_Red']

for column in column_names: 
    h_column_names.append("H_" + column)
    a_column_names.append("A_" + column)
df_home = data_by_seasons.filter(h_column_names)
df_away = data_by_seasons.filter(a_column_names)

df_home.columns = column_names_new
df_away.columns = column_names_new

df_total = df_home.append(df_away)
df_total.head()

Season       Team  Goals  Goals_Received FT_Result  HT_Goals  \
0    2-3    Chelsea    1.0             1.0         D       1.0   
1    2-3     Bolton    1.0             0.0         H       0.0   
2    2-3  Newcastle    2.0             1.0         H       0.0   
3    2-3  Liverpool    1.0             2.0         A       0.0   
4    2-3      Leeds    1.0             2.0         A       1.0   

   HT_Goals_Received HT_Result  Shots_Target  Shots_Target_Received  Fouls  \
0                0.0         H           2.0                    5.0   20.0   
1                0.0         D           6.0                    5.0    9.0   
2                1.0         A          15.0                    5.0   13.0   
3                0.0         D           7.0                    4.0   13.0   
4                0.0         H           6.0                   10.0   14.0   

   Got_Fouled  Corner  Corner_Received  Yellow  Yellow_Received  Red  \
0        16.0     6.0              2.0     5.0              2.0  0.0   
1        11.0     4.0              5.0     2.0              3.0  0.0   
2        18.0    11.0              2.0     0.0              1.0  0.0   
3        11.0     5.0              2.0     1.0              4.0  0.0   
4        15.0     5.0             11.0     1.0              1.0  0.0   

   Red_Received  Delta_Goals  Delta_HT_Goals  Delta_Shots_On_Target  \
0           1.0          0.0             1.0                   -3.0   
1           0.0          1.0             0.0                    1.0   
2           1.0          1.0            -1.0                   10.0   
3           0.0         -1.0             0.0                    3.0   
4           0.0         -1.0             1.0                   -4.0   

   Delta_Foul  Delta_Corner  Delta_Yellow  Delta_Red  
0         4.0           4.0           3.0       -1.0  
1        -2.0          -1.0          -1.0        0.0  
2        -5.0           9.0          -1.0       -1.0  
3         2.0           3.0          -3.0        0.0  
4        -1.0          -6.0           0.0        0.0

In [85]:
df_total.to_csv('df_total.csv')